### ISSUE TITLE
Inaccurate distance reported

### ISSUE THREAD

**Issue by ernstvanzyl** [rsc1975/micropython-hcsr04#10]
My mm calculation is (pulse_time + 68) / 5.804
My guess is the Python interpreter takes some time before it actually gets to execute time_pulse_us

**Comment by rsc1975** [comment]
Hi @ernstvanzyl The driver was developed a long time ago, and this is the first time someone reports an accuracy issue, I doubt that the problem is related with the driver, maybe the micropython version or a HW issue... On the other hand if you have tested it in an environment very wet the measurements can vary significantly.

Maybe, if you provide further details we can help you more properly

**Comment by ernstvanzyl** [comment]
I used a AJ-SR04M in the open atmosphere.
I took these results:
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/ernst/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/ernst/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">



</head>

<body link="#0563C1" vlink="#954F72">



Distance | Pulse time | Calc | Form1
-- | -- | -- | --
200 | 1128 | 206.0648 | 193.8144
300 | 1685 | 302.0331 | 289.5189
400 | 2250 | 399.3797 | 386.5979
500 | 2834 | 500 | 486.9416
600 | 3416 | 600.2757 | 586.9416
700 | 4009 | 702.4466 | 688.8316
1000 | 5736 | 1000 | 985.567



</body>

</html>
<p>Form1 = pulse_time / 5.82</p>
<p>Calc =  (pulse_time + 68) / 5.804</p>

**Comment by rsc1975** [comment]
It's interesting, the deviation is not linear, from 400mm is always about 13-15mm under the real distance. I've never used this sensor model, according to what I've read, the operational range is from 20cm to 8m and the resolution is 5mm. So the measurement should be more accurate, theoretically.

I cannot test it with a real sensor, so I'm afraid I cannot help you too much, what I'd do is to sum 12/13mm to the result, so you'll get a more accurate value, close enough to the real distance, I mean, under the supported resolution by the sensor (5mm). Or fork the repo and change the algorithm to fit with your formula....

**Comment by ernstvanzyl** [comment]
If you look at the table you'll notice that  Calc = (pulse_time + 68) / 5.804 is accurate above 200mm. I made a plot in Excel and the data lies pretty much on a straight line. BTW I get pretty much the same results in C++ so this post is just me commenting on this phenomenon and not trying to point out an issue with the driver.
