### ISSUE TITLE
Echo Time

### ISSUE THREAD

**Issue by luylucas10** [rsc1975/micropython-hcsr04#4]
First, thanks.

It's not a issue but a doubt: if I pass another value to the 'echo_timeout_us', does it mean that I can read more than 4m?

If I want to read about 10m, what values can I use?

**Comment by rsc1975** [comment]
The "4m" is the sensor physical limit, you cannot measure a distance greater than 4m with this sensor.

**Comment by luylucas10** [comment]
Ok, I understood. Thank you
