### ISSUE TITLE
Cannot import the file into my code in ESP32

### ISSUE THREAD

**Issue by vivianalinares** [rsc1975/micropython-hcsr04#8]
Hi, 

Although I followed all steps. My board is not able to import the file

>>> %Run -c $EDITOR_CONTENT
Traceback (most recent call last):
  File "<stdin>", line 3, in <module>
ImportError: cannot import name HCSR04
>>>

**Comment by n0r** [comment]
This is due to how micropython uses import path.
We need to modify sys.path to also look on the sdcard / flash.

Check this:
http://wiki.micropython.org/Importing-Modules
https://forum.micropython.org/viewtopic.php?t=121
```
import sys
sys.path.append('0:/')
```
